= Arquillian GlassFish Container Integration

> NOTE: This repository is a fork of the official [arquillian-container-glassfish6](https://github.com/arquillian/arquillian-container-glassfish6)

The original project is not active as expected, so I fork this project and update to use the latest GlassFish 7.0 and Jakarta EE 10.

* Update to Glassfish 7.0 and Jakarta EE 10 APIs to build the project.
* Rename project artifact and add a `-jakarta` postfix.
* Change the Java baseline to Java 11 and clean the source codes.
* Update the tests to use JUnit 5.

== Usage 

I use [Jitpack](https://jitpack.io) to share my work to Java communities. 

Add the following repository in your project pom.xml.

```xml
<repositories>
    //... other repositories
    <repository>
        <id>jitpack.io</id>
        <url>https://jitpack.io</url>
    </repository>
</repositories>
```

To use a *managed GlassFish container adapter*, add the following dependency.

```xml
<dependencies>
    // other dependencies
    <dependency>
        <groupId>com.github.hantsy.arquillian-container-glassfish-jakarta</groupId>
        <artifactId>arquillian-glassfish-managed-jakarta</artifactId>
        <version>${arquillian-glassfish-jakarta.version}</version>
        <scope>test</scope>
    </dependency>
</dependencies>
```

== Build

Clone the project and run the following command in the project root folder:

`mvn clean install`

